### PR TITLE
Update translations (French)

### PR DESCRIPTION
**Pull request by lujjjh**
Co-authored-by: PakkoGraphic <pakkographic@users.noreply.github.com>

### CODE REVIEW

**Comment by pakkographic** [comment]
Thanks for taking the translations I've made, it was nice to help ya!

**Comment by lujjjh** [comment]
@pakkographic Thank you!

**Comment by pakkographic** [comment]
It'd be nice to add the language to the language selection box (even if the fr-fr url works)

**Comment by lujjjh** [comment]
> It'd be nice to add the language to the language selection box (even if the fr-fr url works)

Fixed :)

**Pull request merged**
